# image will be published to ghcr.io/<user>/<name>
name: dumb-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: script
    scripts:
      - omen-fan.sh
      - nautilus-open-any-terminal.sh

  - type: rpmfusion
    install:
      - mpd

  - type: rpm-ostree
    repos:
      - https://pkg.cloudflareclient.com/cloudflare-warp-ascii.repo
      - https://copr.fedorainfracloud.org/coprs/atim/nushell/repo/fedora-%OS_VERSION%/atim-nushell-fedora-%OS_VERSION%.repo
    install:
      # King's Cross and some shells. Protip: kgx --set-shell=fish
      - gnome-console
      - zsh
      - fish
      - dash
      - nushell
      # Not found on Homebrew
      - android-tools
      # (if you want) systemctl enable warp-svc
      # also see https://developers.cloudflare.com/warp-client/get-started/linux/#initial-connection
      - cloudflare-warp
    # remove:
    #   # To reduce redundancy, use flatpak or brew to install these packages 
    #   - firefox
    #   - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
    #   - htop
    #   - nvtop
    #   - ptyxis

  - type: gnome-extensions
    install:
      # Quick Close in Overview: middleclickclose@paolo.tranquilli.gmail.com
      - 352 # Close windows with a middle click when in overview mode
      # AppIndicator and KStatusNotifierItem Support: appindicatorsupport@rgcjonas.gmail.com
      - 615 # Adds back system tray icons. Nice to have for legacy apps, but I would avoid relying on it
      # PiP on top: pip-on-top@rafostar.github.com
      - 4691 # Silly Wayland.
      # App Hider: app-hider@lynith.dev
      - 5895 # Hide apps in GNOME's app menu.

  - type: signing # this sets up the proper policy & signing files for signed images to work fully