# image will be published to ghcr.io/<user>/<name>
name: dumb-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: bling
    install: ["ublue-update"]

  - type: rpm-ostree
    repos:
      - https://repository.mullvad.net/rpm/stable/mullvad.repo
    install:
      - gnome-console
      - mullvad-browser
    remove:
      - gnome-terminal
      - gnome-system-monitor
      - htop
      # removing firefox (in favor of the flatpak)
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: brew

  - type: yafti
    custom-flatpaks:
      - Builder: org.gnome.Builder
      - Decibles (Audio Player): org.gnome.Decibels
      - Papers (Document Viewer): org.gnome.Papers
      - Showtime (Video Player): org.gnome.Showtime
      - Mission Center (System Monitor): io.missioncenter.MissionCenter

  - type: signing # this sets up the proper policy & signing files for signed images to work fully